[package]
name = "RUST"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"       # SHA-256 hashing library
chrono = "0.4"      # Time handling for timestamps
serde = { version = "1.0", features = ["derive"] }  # JSON serialization

